### ISSUE TITLE
handle_event/2 is referenced but does not exist

### ISSUE THREAD

**Issue by gavinhughes** [Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot-source-code#2]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/10154/111898067-a7b2bd80-8a5e-11eb-90bd-7ea8fbbef3cc.png">

**Comment by Cinderella-Man** [comment]
Hello :wave: 

Thank you very much for pointing this out, the description is incorrect - it should point to `process_event/1` - I've updated the description and the code snippet below it to:
```
  # /apps/streamer/lib/streamer/binance.ex
  defp process_event(%{"e" => "trade"} = event) do
    ...
    Naive.send_event(trade_event)
  end
```

Thank you once again for pointing this out :+1:
