### ISSUE TITLE
Duplicated image on chapter 3

### ISSUE THREAD

**Issue by marcoflcn** [Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot-source-code#8]
Hi!
First of all thanks for this book, it covers a lot of useful elixir topics with a concrete interesting project and I'm really enjoying it.
I think that image at the end of 3.2 is duplicated, it should show some sort of database store process as described in the paragraph.

**Comment by Cinderella-Man** [comment]
Hi :wave: 

Thank you very much for pointing this out and I'm super happy that you are enjoying the book - the source code of the actual book is in the other repository - I just created a pull request, merged, and released a new version 0.1.5 which will include the fix to this issue(https://github.com/frathon/create-a-cryptocurrency-trading-bot-in-elixir/pull/8).

Thank you very much once again for taking the time to report this and improving the book :+1:
